In [ ]:
import torchvision.datasets as dsets
dsets.CIFAR10

In [11]:
import torch
cls = torch.rand([256])
cls.unsqueeze(0) != cls.unsqueeze(1)
# y = (cls.unsqueeze(0) != cls.unsqueeze(1)).float().view(-1)
# y.shape

tensor([[False,  True,  True,  ...,  True,  True,  True],
        [ True, False,  True,  ...,  True,  True,  True],
        [ True,  True, False,  ...,  True,  True,  True],
        ...,
        [ True,  True,  True,  ..., False,  True,  True],
        [ True,  True,  True,  ...,  True, False,  True],
        [ True,  True,  True,  ...,  True,  True, False]])

In [27]:
y_hat = torch.rand([256,48])
dist = ((y_hat.unsqueeze(0) - y_hat.unsqueeze(1)) ** 2).sum(dim=2).view(-1)
dist.shape

x = torch.rand([2,3])
print(x)
print(x.view(-1))

tensor([[0.0468, 0.2885, 0.9503],
        [0.9932, 0.4938, 0.5741]])
tensor([0.0468, 0.2885, 0.9503, 0.9932, 0.4938, 0.5741])


In [1]:
import argparse
import torch
from utils.data import get_CIFAR10_data
from utils.util import *
import torch.nn as nn
import torchvision

